server:
  port: 4521

spring:
  datasource:
    url: jdbc:h2:mem:imdb
    driver-class-name: org.h2.Driver
    username: lobox
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    root: info
    com.example.imdbapp: debug

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
